/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GarageAccess {
  export type EmployeeDataStruct = {
    employeeAddress: AddressLike;
    name: string;
    role: BigNumberish;
    status: BigNumberish;
  };

  export type EmployeeDataStructOutput = [
    employeeAddress: string,
    name: string,
    role: bigint,
    status: bigint
  ] & { employeeAddress: string; name: string; role: bigint; status: bigint };
}

export interface GarageAccessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canAccessGarage"
      | "getAllEmployee"
      | "getEmployeeData"
      | "recruitEmployee"
      | "terminateEmployee"
      | "updateEmployeeDetail"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "canAccessGarage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recruitEmployee",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmployeeDetail",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "canAccessGarage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recruitEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminateEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmployeeDetail",
    data: BytesLike
  ): Result;
}

export interface GarageAccess extends BaseContract {
  connect(runner?: ContractRunner | null): GarageAccess;
  waitForDeployment(): Promise<this>;

  interface: GarageAccessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canAccessGarage: TypedContractMethod<
    [_employeeAddress: AddressLike],
    [boolean],
    "view"
  >;

  getAllEmployee: TypedContractMethod<[], [string[]], "view">;

  getEmployeeData: TypedContractMethod<
    [_employeeAddress: AddressLike],
    [GarageAccess.EmployeeDataStructOutput],
    "view"
  >;

  recruitEmployee: TypedContractMethod<
    [_employeeAddress: AddressLike, _name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  terminateEmployee: TypedContractMethod<
    [_employeeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEmployeeDetail: TypedContractMethod<
    [_employeeAddress: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canAccessGarage"
  ): TypedContractMethod<[_employeeAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllEmployee"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEmployeeData"
  ): TypedContractMethod<
    [_employeeAddress: AddressLike],
    [GarageAccess.EmployeeDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recruitEmployee"
  ): TypedContractMethod<
    [_employeeAddress: AddressLike, _name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "terminateEmployee"
  ): TypedContractMethod<[_employeeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEmployeeDetail"
  ): TypedContractMethod<
    [_employeeAddress: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
