/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GarageAccess } from "./GarageAccess";
export type { Web3bridge } from "./Web3bridge";
export * as factories from "./factories";
export { GarageAccess__factory } from "./factories/GarageAccess__factory";
export { Web3bridge__factory } from "./factories/Web3bridge__factory";
