/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GarageAccess__factory } from "./GarageAccess__factory";
export { Web3bridge__factory } from "./Web3bridge__factory";
