/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DynamicTimeSVGNFT__factory } from "./DynamicTimeSVGNFT__factory";
export { TimeNFT__factory } from "./TimeNFT__factory";
